name: E2E regression
on:
  push:
    branches:
      - master

jobs:
  Cypress-Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v4

      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run runTesting

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress artifacts
          path: |
            cypress/reports/html/index.html
          retention-days: 30
